### ISSUE TITLE
周报素材

### ISSUE THREAD

**Issue by TangMisaka23001** [TangMisaka23001/TangMisaka23001.github.io#8]
- [x] bbr

**Comment by 913647909** [comment]
>     * [ ]  bbr

[BBR+BBR魔改+Lotsever(锐速)一键脚本 for Centos/Debian/Ubuntu](https://www.moerats.com/archives/387/)

**Comment by TangMisaka23001** [comment]
#13 骑行听的播客
萨勒姆的女巫

**Comment by TangMisaka23001** [comment]
[Jib](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin)
Jar部署docker的maven插件

**Comment by TangMisaka23001** [comment]
[git cz](http://commitizen.github.io/cz-cli/)
一个规范化git提交的工具

**Comment by TangMisaka23001** [comment]
[Azure Devops](https://dev.azure.com/mikasatang/first_devops)
Azure提供的devops流程工具

**Comment by TangMisaka23001** [comment]
skipList数据结构
一致性Hash
Dubbo SPI机制

**Comment by TangMisaka23001** [comment]
> 
> 
> skipList数据结构
> 一致性Hash
> Dubbo SPI机制

https://www.cnblogs.com/GrimMjx/p/10970643.html
http://dubbo.apache.org/zh-cn/blog/introduction-to-dubbo-spi.html
http://dubbo.apache.org/zh-cn/blog/introduction-to-dubbo-spi-2.html
https://izhen.me/2018/07/15/consistentHash/
https://www.iteye.com/blog/javatar-1123915

**Comment by TangMisaka23001** [comment]
锁 
https://zh.wikipedia.org/wiki/%E9%94%81_(%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%A7%91%E5%AD%A6)

**Comment by 913647909** [comment]
spring test
[有赞单元测试实践](https://tech.youzan.com/youzan-test-practice/)
